# Generated by Django 4.2.5 on 2023-12-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumpar_carti', '0002_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'managed': True, 'verbose_name': 'Header-Paragraf', 'verbose_name_plural': 'Header-Paragrafe'},
        ),
    ]
