# Generated by Django 4.2.5 on 2023-12-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumpar_carti', '0003_alter_header_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='HeaderParagraf',
        ),
    ]
